### ISSUE TITLE
ProtectionStones 1.4 - Problem hide|unhide

### ISSUE THREAD

**Issue by Therufianx** [vik1395/ProtectionStones-Minecraft#4] opened 2016-09-27 11:59 UTC
https://youtu.be/hdE7f6YZR7Q

**Comment by vik1395** [comment] 2016-09-27 22:12
Hey, this issue has been fixed in the new update by Dragoboss. You can download it from **[HERE](https://www.spigotmc.org/resources/protectionstones.10096/download?version=116477)**

**Comment by Therufianx** [comment] 2016-09-27 23:31
same error :/

**Comment by Dragoboss** [comment] 2016-09-28 19:38
Try this hotfix version:
https://github.com/vik1395/ProtectionStones-Minecraft/blob/master/target/ProtectionStones-1.4.1b.jar

Tell me the result ;)
It should prevent /ps hide when already hidden and /ps unhide when already visible.

**Comment by Therufianx** [comment] 2016-09-28 22:55
thanks

**Comment by Therufianx** [comment] 2016-09-29 06:22
I have another problem :/
old ProtectionStone version 1.3.2 in the new version, i use /unhide
and..

29.09 00:16:50 [Server] INFO UUID of player JoshuaSahian is 069bc2a9-a04c-3559-baaf-aa0868596f31
29.09 00:16:37 [Server] INFO ... 15 more
29.09 00:16:37 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:37 [Server] INFO at me.vik1395.ProtectionStones.Main.onCommand(Main.java:407) ~[?:?]
29.09 00:16:37 [Server] INFO Caused by: java.lang.NullPointerException
29.09 00:16:37 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
29.09 00:16:37 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:37 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:37 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:37 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:37 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:37 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
29.09 00:16:37 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
29.09 00:16:37 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:37 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:37 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:37 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:37 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:37 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:37 [Server] INFO at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) ~[?:?]
29.09 00:16:37 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:37 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ps' in plugin ProtectionStones v1.4.1b
29.09 00:16:37 [Server] ERROR null
29.09 00:16:37 [Multicraft] Skipped 4 lines due to rate limit (30/s)
29.09 00:16:29 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
29.09 00:16:29 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
29.09 00:16:29 [Server] INFO at sun.reflect.GeneratedMethodAccessor306.invoke(Unknown Source) ~[?:?]
29.09 00:16:29 [Server] INFO at me.wazup.kitbattle.AbilityListener.AbilityInteractEvent(AbilityListener.java:63) ~[?:?]
29.09 00:16:29 [Server] INFO at me.wazup.kitbattle.AbilityListener.hasKit(AbilityListener.java:705) ~[?:?]
29.09 00:16:29 [Server] INFO Caused by: java.lang.NullPointerException
29.09 00:16:29 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
29.09 00:16:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
29.09 00:16:29 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
29.09 00:16:29 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:623) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins1.8.1.jar:?]
29.09 00:16:29 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:16:29 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
29.09 00:16:29 [Server] INFO org.bukkit.event.EventException
29.09 00:16:29 [Server] INFO Could not pass event PlayerInteractEvent to KitBattle v2.1
29.09 00:16:29 [Server] ERROR **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
29.09 00:16:29 [Disconnect] User JoshuaSahian has disconnected, reason: You interacted too fast!
29.09 00:16:20 [Multicraft] JoshuaSahian ran command Message of the Day
29.09 00:16:20 [Connect] User JoshuaSahian, IP 189.217.35.42
29.09 00:16:20 [Server] INFO UUID of player JoshuaSahian is 069bc2a9-a04c-3559-baaf-aa0868596f31
29.09 00:16:08 [Server] INFO Database have been background saved!
29.09 00:16:08 [Multicraft] Skipped 8 lines due to rate limit (30/s)
29.09 00:15:59 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
29.09 00:15:59 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
29.09 00:15:59 [Server] INFO at sun.reflect.GeneratedMethodAccessor306.invoke(Unknown Source) ~[?:?]
29.09 00:15:59 [Server] INFO at me.wazup.kitbattle.AbilityListener.AbilityInteractEvent(AbilityListener.java:63) ~[?:?]
29.09 00:15:59 [Server] INFO at me.wazup.kitbattle.AbilityListener.hasKit(AbilityListener.java:705) ~[?:?]
29.09 00:15:59 [Server] INFO Caused by: java.lang.NullPointerException
29.09 00:15:59 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
29.09 00:15:59 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
29.09 00:15:59 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
29.09 00:15:59 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:623) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:227) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins1.8.1.jar:?]
29.09 00:15:59 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:59 [Server] INFO at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
29.09 00:15:59 [Server] INFO org.bukkit.event.EventException
29.09 00:15:59 [Server] INFO Could not pass event PlayerInteractEvent to KitBattle v2.1
29.09 00:15:59 [Server] ERROR **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
29.09 00:15:59 [Disconnect] User JoshuaSahian has disconnected, reason: You interacted too fast!
29.09 00:15:06 [Server] INFO ... 15 more
29.09 00:15:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:06 [Server] INFO at me.vik1395.ProtectionStones.Main.onCommand(Main.java:407) ~[?:?]
29.09 00:15:06 [Server] INFO Caused by: java.lang.NullPointerException
29.09 00:15:06 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
29.09 00:15:06 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:06 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:06 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:06 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:06 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:06 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
29.09 00:15:06 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
29.09 00:15:06 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:06 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:06 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:06 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:06 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:06 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:06 [Server] INFO at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) ~[?:?]
29.09 00:15:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8-20150820a.jar:git-Spigot-fdc1440-53fac9f]
29.09 00:15:06 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ps' in plugin ProtectionStones v1.4.1b
29.09 00:15:06 [Server] ERROR null

**Comment by Therufianx** [comment] 2016-09-29 06:52
i have another problem :/ the command doesn't work /ps tp player 1
I guess used to teleport other protections of other players but only leads me to my first protection
thanks

**Comment by Dragoboss** [comment] 2016-09-29 12:30
Can you try a clean install of the plugin, re-add existing configurations later?
I have been testing but cannot find any comparable issues with the commands to yours.

Which server version are you using? 1.8, 1.9 or 1.10?

**Comment by Therufianx** [comment] 2016-09-29 14:31
1.8.8
spigot-1.8.8-20150820a.jar

**Comment by Dragoboss** [comment] 2016-09-30 13:47
I have ran 1.4.1b without any direct issues on spigot 1.8.8 today.
Have you done a clean run, like I said?

If not, please simple rename your current ProtectionStones folder to something else (functions as a backup), and let the plugin create the folder and all its files freshly, then test for errors.
If it runs without error slowly start putting the settings back as they were, see if it keeps running without any error.
If it causes errors right away, please see if it also errors in a server with just WorldEdit, WorldGuard, any permissions plugin and PStones on it. If it doesn't the error seems to be caused by another of your plugins, in this case hand me a list of your current plugins in a pastebin or private message on spigotmc.org (in case you wish to keep them secret) and I'll test each one of them out one by one.

**Closed as completed** 2017-07-10 07:12 UTC
Labels: bug
